services:
  shadownetdb:
    container_name: shadownetdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shadownetdb
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_shadownetdb:/var/lib/postgresql/data

  seq:
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - 5341:5341
      - 9091:80