services:
  shadownetdb:
    container_name: shadownetdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shadownetdb
    restart: always
    ports:
      - 5432:5432

  seq:
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - 5341:5341
      - 9091:80

  redis:
    container_name: redis
    restart: always
    ports:
      - 6379:6379