@ShadowNetBackend_HostAddress = https://localhost:7029
@AgentId = 5a1a918c-a657-404b-b2ea-1759560f3659

DELETE {{ShadowNetBackend_HostAddress}}/api/agents/{{AgentId}}

###

GET {{ShadowNetBackend_HostAddress}}/api/agents

###
